[tox]
min_version = 4.0
envlist =
    py314
    codestyle

[testenv]
skip_install = true
description =
    run checks and the script
deps =
    -r requirements.txt
commands =
    pip freeze --all --no-input
    python test_scraper.py
    python scraper.py

[testenv:codestyle]
description = Run all style, type and file checks
deps =
    -r requirements-dev.txt
commands =
    pre-commit install-hooks
    pre-commit run --color always --all-files --show-diff-on-failure
    ty check
